### ISSUE TITLE
Add users and friends

### ISSUE THREAD

**Issue by SeanHRKong** [MayAbrantes/learningRuby#2]
As a MassiveAttacker user I want to:

- [ ] be able to 'Sign Up' and create a user profile
- [ ] be able to 'Sign In' with an existing username and password and Sign Out
- [ ] be able to 'Edit Profile'
- [ ] search and filter other 'Users'
- [ ] add and remove other 'Users' as 'Friends'
- [ ] be able to see 'Friends' list and profiles
